app:
  build: .
  command: python server.py
  volumes:
    - ./src:/app
  working_dir: /app
  ports:
      - "2046:2046"     # UDP端口
      - "2047:2047"     # telnet 端口
#  environment:
#   - DEBUG_PYSOLR= "0"
  restart: always