app:
  build: .
  command: python server.py
  volumes:
    - ./src:/app
  working_dir: /app
  ports:
      - "6800:6800/udp"     # UDP端口
      - "6801:6801"     # telnet 端口
#  environment:
#   - DEBUG_PYSOLR= "0"
  restart: always
